{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "hello-v2.serviceAccountName" . }}
  labels:
{{ include "hello-v2.labels" . | indent 4 }}
{{- end -}}
